### PR TITLE
[BRAAV-786] Add smokebox support to sample app

### PR DESCRIPTION
**Pull request by mboorstin-circle**

### CODE REVIEW

**Comment by mboorstin-circle** [comment]
`fatal: could not read Username for 'https://github.com': No such device or address` Hmmm.

**Comment by mboorstin-circle** [comment]
@MasterXen this is ready for re-review; I've filed https://console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=6956564981&language=enwith AWS support to figure out what's going on with the PR builder.

**Comment by creilly12** [comment]
@mboorstin-circle recommend that you kick a build somehow. I suspect this was related to the github issues yesterday. I see several successful pull request builds for the same app.

**Comment by mboorstin-circle** [comment]
@creilly12 I did (which is why it's now green).

**Pull request merged**
